[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[[headers]]
  for = "/assets/images/og-preview.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Access-Control-Allow-Origin = "*"
